### ISSUE TITLE
Sugestion for the structure of your project 😊

### ISSUE THREAD

**Issue by Fziliotti** [EsdrasChaves/simple-react-boilerplate#1]
Hi my friend, **if you want** check [this react structure](https://daveceddia.com/react-project-structure/)  to study a pattern of structure for this boilerplate! 😃

If you have questions about the difference between components and containers like me, check this
[post of Medium](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) too.
👍😉

**Comment by EsdrasChaves** [comment]
Thanks a lot!! I'll definitely check it out xD
